### PR TITLE
Issue-171 Update tests and patches to support Drupal 8.4

### PR DESCRIPTION
**Pull request by mrkmiller**

### CODE REVIEW

**Comment by dearmond** [comment]
Woohoo! All tests pass!

**Comment by mrkmiller** [comment]
Looks like the 8.5 inheritance patch failed to apply.

**Comment by dearmond** [comment]
Yes I noticed. I'll just using it temporarily so I can test the patch agains 8.5.x-dev. I'll revert that last commit when I'm done.

**Comment by mrkmiller** [comment]
I'm not allowed to review this so someone else will need to.

**Review by dearmond — APPROVED** [review]

**Comment by dearmond** [comment]
I'd like to see one more campus, other than UCD approve these changes.

@eguerin-ucsf @ellyjonez would you please "Review" and "Approve"?

**Comment by ellyjonez** [comment]
I can certainly add my review but not having been in the code I don't know how much weight it holds. Glad to see we're using Chromedriver for tests though 👍

**Review by ellyjonez — APPROVED** [review]

**Pull request merged**
