### PR TITLE
Update Drupal core and patches for 8.5.4

### PR DESCRIPTION
**Pull request by cboyden-ucb**

### CODE REVIEW

**Comment by cboyden-ucb** [comment]
Site install through the UI succeeded locally - no exceptions.

**Comment by dearmond** [comment]
Add: `And I wait 2 seconds` to tests/features/photo_gallery.feature at line 15 between the two image upload steps. We just had to do this for our tests too. They moved too fast when javascript was being fired.

**Comment by dearmond** [comment]
tests/features/article_views.feature:99 is still giving grief.

**Comment by dearmond** [comment]
Also, you can't include the `web` in `"web/modules/contrib/{$name}":` in the composer.json. It won't always be "web".

**Comment by mrkmiller** [comment]
Actually...
```
    "installer-paths": {
      "modules/contrib/{$name}": [
        "type:drupal-module"
      ],
      "themes/contrib/{$name}": [
        "type:drupal-theme"
      ]
    },
```
can be removed altogether. I don't believe installer paths are read from a dependency composer.json file anyway. All installer-paths should be set in the parent (distribution) composer.json file.

**Comment by mrkmiller** [comment]
This worked for me. Composer installed and Drupal installed the sub profile.

I'm not sure yet how I feel about putting in a Drupal verison as a requirement `"drupal/core": "~8.5.4",`. This will have to be changed again in order to move to 8.6.x. My thought was always that if someone needed a fixed Drupal version then they could put it as a requirement in their distro composer.json file. Otherwise they will have a conflict if they try to move on before we have updated the profile.

**Comment by cboyden-ucb** [comment]
@mrkmiller the constraint should support any release that's >=8.5.4 and <8.6.0. 

8.6.0 will most likely drop in October; when that happens, we'll be dealing with what phenaproxima mentions in https://www.drupal.org/project/drupal/issues/1356276?page=1#comment-12545937 : "a lot of what the profile handler does, could be done by the new extension.list.profile service that was added to 8.6.x" 

It's pretty likely that any patch written for 8.5.x will fail to apply to 8.6.x. So we'd have to do some major work and testing at that point anyway, because the base profile patch will either be superfluous, or need to be entirely reworked.

**Comment by mrkmiller** [comment]
> It's pretty likely that any patch written for 8.5.x will fail to apply to 8.6.x. So we'd have to do some major work...

I think that's my concern. By requiring a specific drupal core version, people have no choice but to wait for this profile to update before they can move forward. By allowing people to decide on the version of Drupal that they need, they can use whatever patch works for them or roll their own. No one is locked into the patches from this profile because in their distro composer.json they can specify an override like:
```
"patches": {
  "drupal/core": {
    "Profile Inheritance v4": "https://www.drupal.org/files/issues/1356276-408--8.4.x.patch"
  }
},
"patches-ignore": {
  "ucdavis/sitefarm_seed": {
    "drupal/core": {
      "Profile Inheritance": "https://www.drupal.org/files/issues/1356278-408--8.5.x-real.patch"
    }
  }
}
```
Overriding a package dependency is a little more complicated requiring branching repos and setting up aliases. I'm not sure the benefit of fixing a minor drupal version is worth the possible headaches it can cause. As much as possible we were trying to not lock people into things that they couldn't change in their distro composer file.

**Comment by cboyden-ucb** [comment]
Thanks @mrkmiller, I've updated the composer.json:
`"drupal/core": "^8.5.4",`
Let me know if it should be less restrictive still. I think maybe this will get the balance between distros not having to override the patch and keeping up with future updates. I'm pretty sure the base profile stuff has moved fast enough that the patch I'm using won't apply to versions earlier than 8.5.4.

**Review by mrkmiller — APPROVED** [review]

**Comment by dearmond** [comment]
I got Probo to acknowledge that this repo exists. Now trying to get it to trigger the build.

**Review by dearmond — APPROVED** [review]

**Review by eguerin-ucsf — APPROVED** [review]
Looks good.

**Review by eguerin-ucsf — APPROVED** [review]
This looks more in line with expectations for the non-parent profile.

**Pull request merged**
